"""Added user quote reaction table

Revision ID: 0531cbf58b15
Revises: 29abf28c0d9c
Create Date: 2025-09-18 11:06:38.383858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0531cbf58b15'
down_revision: Union[str, Sequence[str], None] = '29abf28c0d9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_quote_reactions',
    sa.Column('reaction_id', sa.Uuid(), nullable=False),
    sa.Column('like', sa.Boolean(), nullable=True),
    sa.Column('dislike', sa.Boolean(), nullable=True),
    sa.Column('quote_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.quote_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('reaction_id')
    )
    op.create_index(op.f('ix_quotes_quote_id'), 'quotes', ['quote_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quotes_quote_id'), table_name='quotes')
    op.drop_table('user_quote_reactions')
    # ### end Alembic commands ###
