"""added audit columns

Revision ID: af0237569f5c
Revises: 0531cbf58b15
Create Date: 2025-09-19 10:53:09.302589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'af0237569f5c'
down_revision: Union[str, Sequence[str], None] = '0531cbf58b15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    op.add_column('quotes', sa.Column('created_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('quotes', sa.Column('updated_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('user_quote_reactions', sa.Column('created_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('user_quote_reactions', sa.Column('updated_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('user_quote_reactions', 'updated_at')
    op.drop_column('user_quote_reactions', 'created_at')
    op.drop_column('quotes', 'updated_at')
    op.drop_column('quotes', 'created_at')
    op.create_table('products',
    sa.Column('id', mysql.CHAR(length=32), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('price', mysql.FLOAT(), nullable=True),
    sa.Column('category', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('stock_quantity', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
